from typing import Optional, List
from pydantic import BaseModel, Field

class QueryRequest(BaseModel):
    question: str = Field(..., description="The input question for the RAG pipeline.")
    image: Optional[str] = Field(None, description="Base64 or URL image input for future vision processing.")
    top_k: Optional[int] = Field(None, description="Optional override for vector retrieval top_k.")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="Grounded answer generated by LLM.")
    sources: List[str] = Field(default_factory=list, description="Unique list of cited source document names.")
    detections: Optional[List[dict]] = Field(None, description="Object detection bounding boxes reserved for future vision feature.")
